version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-with-env
      args:
        REACT_APP_API_ENDPOINT: "http://localhost:8080/api"
        REACT_APP_WS_ENDPOINT: "ws://localhost:8080"
        PORT: 8080
    ports:
      - "8080:8080"
    environment:
      PROD_MONGODB_URI: ${{ PROD_MONGODB_URI}}
      PORT: 8080
      NODE_ENV: "production"
      SECRET: "supersecret"
